config/routes.rb
Rottenpotatoes::Application.routes.draw do
  #resources :movies
  # map '/' to be a redirect to '/movies'
  resources :resume, only: [:new, :create]
  root :to => redirect('/resume')

  get '/resume', to: 'resume#new', as: 'resume'

  get '/uploaded', to: 'resume#uploaded', as: 'uploaded'

  post '/tailor', to: 'resume#tailor', as: 'tailor'

  get '/download', to: 'resume#download', as: 'download'

  get '/editor', to: 'resume#editor', as: 'editor'

  post '/resume/save', to: 'resume#save'

  get 'cancel', to: 'resume#cancel', as: 'cancel'
end

app/models/resume.rb
class Resume < ActiveRecord::Base
  has_one_attached :attachment

  attribute :title, :string unless column_names.include?('title')
  validates :attachment, presence: true, if: -> { resume_text.blank? }
  validates :resume_text, presence: true, if: -> { attachment.blank? }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Your code here
  protect_from_forgery with: :exception
end

app/controllers/resume_controller.rb
require 'pdf-reader'
require 'prawn'

class ResumeController < ApplicationController
  require_relative '../services/gpt3_service'
  @tailored_resume_for_download = ""

  def new
    @resume = Resume.new
  end

 def create
    # puts "Made it to create"
    
    @resume = Resume.new(resume_params)
    if params[:resume][:resume_text].present?
      @resume.title = params[:resume][:resume_text]
    elsif params[:resume][:attachment].present?
      @resume.title = ' '
      # @pdf_reader = PDF::Reader.new(params[:resume][:attachment].tempfile.path)
      # @pdf_reader.pages.each do |page|
      #   @resume.title += page.text
      # end

      begin
        @pdf_reader = PDF::Reader.new(params[:resume][:attachment].tempfile.path)
        @pdf_reader.pages.each
        @pdf_reader.pages.each do |page|
          @resume.title += page.text #this works, i tested with puts
        end
      rescue PDF::Reader::MalformedPDFError => e
        flash[:error] = "Error parsing PDF: #{e.message}"
        redirect_to resume_path and return
      end

    else
      @resume.title = 'None, Error'
    end

    if @resume.save
      # puts "Saves correctly"
      # puts "Uploaded resume title: #{@resume.title}"
      flash[:notice] = "Resume uploaded successfully."
      flash[:alert] = "Warning: you have not yet tailored your resume for editing or downloading"
      # flash[:alert] = @resume.title
      redirect_to uploaded_path
    else
      # puts "In the else statement"
      # flash[:error] = "Failed to upload resume. Please try again."
      # flash[:alert] = "Failed to upload resume. Please try again."
      # flash[:notice] = "Failed to upload resume. Please try again."
      # redirect_to resume_path
      render 'new'
    end
  end

 def tailor
  
    @last_resume = Resume.last
    # puts "here"
    # @last_resume.attributes.each do |attr, value|
    #   puts "#{attr}: #{value}"
    # end
    description = params[:description]

    if description == ""
      flash[:alert] = "Warning: you have not tailored your resume for editing or downloading"
      flash[:notice] = "No description, try again"
    else
      # flash[:alert] = "Success! You can preview or download"
      flash[:notice] = nil

      # Change resume with AI
      @prompt = "Tailor the following resume to match the job description. Don't lie, but rather enhance the resume to just fit the description better. Also, try to keep each line length roughly the same and the number of lines roughly the same from the original resume to the tailored resume. :\n\nJob Description: #{description}\n\nResume: #{@last_resume.title} \n\nTailored Resume:"
      # @prompt = "Tailor the following resume to match the job description. Don't lie, but rather enhance the resume to just fit the description better. Also, try to keep each line length roughly the same and the number of lines roughly the same from the original resume to the tailored resume. :\n\nJob Description: #{description}\n\nResume: #{@resume.title} \n\nTailored Resume:"
      @tailored_resume = Gpt3Service.call(@prompt, 'gpt-3.5-turbo-0301')

      @last_resume.title = @tailored_resume.gsub('\n', "\n")
      @last_resume.resume_text = @tailored_resume.gsub('\n', "\n")
      @last_resume.save

    end
    redirect_to uploaded_path
  end


def download
  tailored_resume = Resume.last

  if tailored_resume
    pdf_content = generate_pdf(tailored_resume.resume_text)
    if pdf_content.present?
      send_data pdf_content, filename: 'tailored_resume.pdf', type: 'application/pdf', disposition: 'attachment'
    else
      flash[:alert] = "Error generating PDF content."
      redirect_to uploaded_path
    end
  else
    flash[:alert] = "No tailored resume is available for download."
    redirect_to uploaded_path
  end
end

def generate_pdf(content)
  pdf = Prawn::Document.new
  pdf.text content
  pdf_content = pdf.render
  pdf_content
end 
 
def editor
  @resume = Resume.last || Resume.new
  @editor_helper = @resume.resume_text || "No Resume"
  
  if !@tailored_resume.present?
  #   @title_helper = 'tailored_resume.txt'
  #   @editor_helper = @tailored_resume
  # else
    flash[:notice] = "No resume was tailored"
  end
end

def save
  @resume = Resume.last

  if @resume.update(resume_params)
    flash[:notice] = "Success! Resume Updated"
    redirect_to uploaded_path
  else
    # flash[:error] = "Failed to update resume. Please try again."
    render :editor
  end
end


  def cancel
    flash[:notice] = "Your resume was not changed"
    redirect_to uploaded_path
  end

  def resume_params
    params.require(:resume).permit(:attachment, :resume_text, :file, :filename, :title) # Include :resume_text in permitted params
  end
end

app/helpers/resume_helper.rb
module ResumeHelper
end

app/views/layouts/_flash.erb
<% if flash[:notice] %>
  <div class="alert alert-info" role="alert" id="notice">
    <%= flash[:notice] %>
  </div>
<% elsif flash[:warning] %>
  <div class="alert alert-danger" role="alert" id="warning">
    <%= flash[:warning] %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>T(ai)lor</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', 'media' => 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
    <style>
      /* Add custom CSS for vertical centering */
      .navbar {
        display: flex;
        align-items: center;
        justify-content: space-between; /* Align items at both ends */
        height: 80px; /* Adjust the height as needed */
        background-color: rgba(30, 30, 30, 1);
        color: white;
        margin-bottom: 20px;
      }

      .title {
        padding-left: 10px;
        padding-top: 5px;
        font-family: Didot, sans-serif;
        font-weight: bold; /* Make the font bold */
	margin-top: 3px; /* Remove default margin for h1 element */
	letter-spacing: 0.8px;
      }

      .ai-text {
        color: rgba(98, 158, 202, 1); /* Set the color for 'AI' text */
      }

      .secondary-title {
        padding-right: 10px;
        padding-top: 5px;
        font-family: Verdana, sans-serif;
        /*font-weight: bold;*/ /* Make the font bold */
	margin-top: 3px; /* Remove default margin for h1 element */
	font-size: 120%;
	letter-spacing: 0.4px;
      }
    </style>
  </head>
  <body>
    <%# These classes come from the Bootstrap CSS framework. %>
    <nav class="navbar navbar-expand-lg">
      <h1 class="title">t<span class="ai-text">AI</span>lor</h1>
      <h1 class="secondary-title">Powered by ChatGPT 3.5</h1>
    </nav>
    <div class="container">
      <%# Render "flash" messages in our application. This loads _flash.erb %>
      <%= render 'layouts/flash' %>
      <main id="main">
        <%= yield %>
      </main>
    </div>
  </body>
</html>

app/views/resume/editor.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <style>
    body {
      background-color: rgba(50, 50, 50, 1.0);
      color: white;
      font-family: Verdana, sans-serif;
    }

    .button-container {
      display: flex;
      gap: 10px;
      margin-top: 20px;
      align-items: center;
    }

    .form-control {
      height: 400px;
      width: 75vw;
      margin-bottom: 40px;
    }

    .save-button,
    .cancel-button,
    .new-resume-button {
      width: 225px; /* Adjust the width as needed */
      border-radius: 10px;
      padding: 8px;
      box-shadow: 0 0 15px rgba(98, 158, 202, 0.5); /* Glow effect */
      transition: background-color 0.3s, color 0.3s;
      line-height: 30px;
      text-align: center;
      text-decoration: none;
      display: inline-block;
    }



    .save-button {
      background-color: rgba(98, 158, 202, 1);
      color: white;
      border: 1px rgba(98, 158, 202, 1);
     }

    .save-button:hover,
    .save-button:focus,
    .save-button:active {
      background-color: rgba(39, 86, 120, 1);
      color: white;
      border: 1px rgba(39, 86, 120, 1);
      text-decoration: none;
    }


    .cancel-button {
      background-color: rgba(7, 61, 110, 1);
      color: white;
      border: 1px rgba(7, 61, 110, 1);
    }

    .cancel-button:hover,
    .cancel-button:focus,
    .cancel-button:active {
      background-color: rgba(5, 31, 55, 1);
      color: white;
      border: 1px rgba(5, 31, 55, 1);
      text-decoration: none;
    }


    .new-resume-button {
      background-color: rgba(66, 19, 19, 1);
      color: white;
      border: 1px rgba(66, 19, 19, 1);
    }

    .new-resume-button:hover,
    .new-resume-button:focus,
    .new-resume-button:active {
      background-color: rgba(40, 12, 12, 1);
      color: white;
      border: 1px rgba(40, 12, 12, 1);
      text-decoration: none;
    }

  </style>
</head>
<body>

  <h2>Resume Editor</h2>

  <%= form_for @resume, url: resume_save_path, method: :post, class: 'form' do |f| %>
    <%= f.label :resume, 'Resume', class: 'col-form-label' %>
    <%= f.text_area :resume_text, class: 'form-control my-own-class', style: 'height: 400px; width: 75vw', value: @editor_helper %>
    <div class="button-container">
      <%= f.submit 'Save', class: 'save-button' %>
      <%= link_to 'Cancel', cancel_path, class: 'cancel-button' %>
      <%= link_to 'Upload New Resume', root_path, class: 'new-resume-button' %>
    </div>
  <% end %>
  <br>
  <br>

</body>
</html>

app/views/resume/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <style>
    body {
      background-color: rgba(50, 50, 50, 1.0);
      color: white;
      font-family: Verdana, sans-serif;
    }

    #typing-container {
      margin: 0 auto;
      word-wrap: break-word;
      text-align: left;
      height: 240px;
    }

    p {
      font-size: 20px;
      line-height: 1.6;
      overflow: hidden;
      display: inline-block;
      margin: 0;
    }

    .upload-paragraph {
      margin-bottom: 20px; /* Adjust the margin-bottom as needed */
      margin-top: -16px;
    }

    .rectangle {
      border: 1px solid white;
      border-radius: 10px; /* Adjust the border radius as needed */
      padding: 10px; /* Adjust the padding as needed */
      box-shadow: 0 0 15px rgba(98, 158, 202, 0.5); /* Glow effect */
      height: 300px; /* Adjust the height as needed */
      display: flex;
      flex-direction: column;
      justify-content: flex-start;
      align-items: center;
    } 

    .field {
      margin-bottom: 10px; /* Adjust the margin-bottom as needed */
    }

    .white-background {
      background-color: white;
      color: black;
      width: calc(100% - 20px); /* Adjust the width as needed */
      margin: 0 auto; /* Center the text area */
      height: 226px;
    }

    .label-wrapper {
      text-align: center;
      margin-bottom: 10px; /* Adjust as needed for vertical spacing */
      font-weight: bold;
    }

    .upload-label {
      margin-bottom: 86px; /* Add a bottom margin to this label */
    }

    #upload-button {
      width: 200px; /* Adjust the width as needed */
      background-color: white;
      color: black;
      border: 1px solid white;
      border-radius: 10px;
      padding: 10px;
      box-shadow: 0 0 105px rgba(255, 255, 25598, 158, 202, 0.5); /* Glow effect */
      margin-top: 20px;
    }

    .typing-char {
      color: rgba(98, 158, 202, 1);
      animation: colorChange 0.5s ease-in-out forwards;
    }

    @keyframes colorChange {
      to {
        color: white;
      }
    }

  </style>
</head>
<body style="background-color: rgba(50, 50, 50, 1.0);">
  <div id="typing-container">
    <p id="typing-text"></p>
  </div>

  <p class="upload-paragraph">Upload or paste your resume below.</p>

  <%= form_for @resume, url: resume_index_path, html: { multipart: true } do |f| %>

    <div class="row">
      <div class="col-md-6 text-center">
        <div class="field rectangle">
          <div class="label-wrapper upload-label">
            <%= f.label :file, 'Upload Your Resume File' %>
          </div>
          <%= f.file_field :attachment %>
        </div>
      </div>

      <div class="col-md-6 text-center">
        <div class="field rectangle">
          <div class="label-wrapper">
            <%= f.label :resume_text, 'Paste Your Resume Text' %>
          </div>
          <%= f.text_area :resume_text, class: 'white-background' %>
        </div>
      </div>
    </div>

    <div class="row">
      <div class="col-md-12 text-center">
        <div class="field">
          <%= submit_tag "Upload Resume", class: 'btn', id: 'upload-button' %>
        </div>
      </div>
    </div>

  <% end %>

  <script>
    // Typing effect
    const text = "Meet Tailor AI, your go-to SaaS for personalized resumes that stand out effortlessly. Powered by ChatGPT 3.5, we refine your resume to match any job description. Just upload your resume, input the desired job details, and Tailor AI crafts a custom-fit resume. With an easy-to-use interface, you can fine-tune the results before downloading your perfectly tailored resume. Elevate your career prospects with Tailor AI – where precision meets opportunity. Your dream job deserves a standout application, and Tailor AI ensures you're ahead of the curve.";

    let index = 0;
    const typingText = document.getElementById('typing-text');

    function type() {
      const char = text[index];
      const charSpan = document.createElement('span');
      charSpan.textContent = char;
      charSpan.className = 'typing-char';
      typingText.appendChild(charSpan);

      index++;

      if (index < text.length) {
        setTimeout(type, 30);
      }
    }

    type();
  </script>
</body>
</html>

app/views/resume/uploaded.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <style>
    body {
      background-color: rgba(50, 50, 50, 1.0);
      color: white;
      font-family: Verdana, sans-serif;
      justify-content: center;      
      align-items: center; 
    }

    .form-container {
      display: flex;
      flex-direction: column;
      align-items: flex-start; /* Left-align */
      padding-bottom: 10px; /* Added 10px padding below the text */
    }

    .button-container {
      display: flex;
      gap: 10px;
      margin-top: 20px;
      justify-content: center;
    }

    .custom-button,
    .tailor-button,
    .new-resume-button,
    .download-resume-button,
    .resume-editor-button {
      width: 225px; /* Adjust the width as needed */
      border-radius: 10px;
      padding: 8px;
      box-shadow: 0 0 15px rgba(98, 158, 202, 0.5); /* Glow effect */
      transition: background-color 0.3s, color 0.3s;
      line-height: 30px;
      text-align: center;
      text-decoration: none;
      display: inline-block;
    }

    .custom-button {
      color: black;
      background-color: rgba(50, 50, 50, 1.0);
      border: 1px solid white;
    }

    .tailor-button {
      outline: none;
      font-family: 'Didot', sans-serif;
      font-weight: bold;
      font-size: 20px;
      margin-left:-15px;
      background-color: white;
      color: black;
      border: 1px solid white;
    }
    
    .ai-text {
      color: rgba(98, 158, 202, 1); /* Set the color for 'AI' text */
    }

    .tailor-button:hover,
    .tailor-button:focus,
    .tailor-button:active {
      background-color: black;
      color: white;
      border: 1px solid black;
      text-decoration: none;
    }

    .download-resume-button {
      background-color: rgba(98, 158, 202, 1);
      color: white;
      border: 1px rgba(98, 158, 202, 1);
    }

    .download-resume-button:hover,
    .download-resume-button:focus,
    .download-resume-button:active {
      background-color: rgba(39, 86, 120, 1);
      color: white;
      border: 1px rgba(39, 86, 120, 1);
      text-decoration: none;
    }

    .resume-editor-button {
      background-color: rgba(7, 61, 110, 1);
      color: white;
      border: 1px rgba(7, 61, 110, 1);
    }

    .resume-editor-button:hover,
    .resume-editor-button:focus,
    .resume-editor-button:active {
      background-color: rgba(5, 31, 55, 1);
      color: white;
      border: 1px rgba(5, 31, 55, 1);
      text-decoration: none;
    }

    .new-resume-button {
      background-color: rgba(66, 19, 19, 1);
      color: white;
      border: 1px rgba(66, 19, 19, 1);
    }

    .new-resume-button:hover,
    .new-resume-button:focus,
    .new-resume-button:active {
      background-color: rgba(40, 12, 12, 1);
      color: white;
      border: 1px rgba(40, 12, 12, 1);
      text-decoration: none;
    }
  </style>
</head>
<body>

  <h5 style="padding-bottom: 10px;">Paste your job description:</h5>
  <%= form_tag tailor_path, method: :post, class: 'form' do %>
    <%= text_area_tag :description, nil, class: 'form-control', style: 'height: 400px; width:75vw; box-shadow: 0 0 15px rgba(98, 158, 202, 0.5)' %>
    <br>

    <div class="container form-container">
      <div class="field button-container">
        <div class="button-group">
          <%= button_tag type: "submit", class: 'tailor-button', onclick: "void(0)" do %>
            t<span class="ai-text">AI</span>lor
          <% end %>
          <%= link_to 'Download Resume', download_path, class: 'download-resume-button' %>
          <%= link_to 'Resume Editor', editor_path, class: 'resume-editor-button' %>
          <%= link_to 'Upload New Resume', root_path, class: 'new-resume-button' %>
        </div>
      </div>
    </div>

    <% if flash[:alert] %>
      <div class="btn btn-outline-secondary"><%= flash[:alert] %></div>
    <% end %>

    <br><br>
  <% end %>
</body>
</html>